app_homepage:
    path: /
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: App\Controller\HomepageController::factoryPatternIndex

app_trait:
    path: /traits
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: App\Controller\HomepageController::traitIndex

app_adapter:
  path: /adapter
  methods: [GET, POST]
  options:
    expose: true
  defaults:
    _controller: App\Controller\HomepageController::adapterPatternIndex

app_decorator:
  path: /decorator
  methods: [GET, POST]
  options:
    expose: true
  defaults:
    _controller: App\Controller\HomepageController::decoratorPatternIndex

app_event:
  path: /event
  methods: [GET, POST]
  options:
    expose: true
  defaults:
    _controller: App\Controller\HomepageController::eventIndex